### PR TITLE
Feat: Generate webhooks on createTeam

### PR DESCRIPTION
**Pull request by Bouncey**

### CODE REVIEW

**Comment by Bouncey** [comment]
Don't merge just yet!!

**Comment by Bouncey** [comment]
@raisedadead I squashed some commits in to @scissorsneedfoodtoo's last commit and now it is holy mess trying to fix it.

Sorry oh `git` master. Please forgive me...

**Comment by Bouncey** [comment]
Good to go!

**Comment by scissorsneedfoodtoo** [comment]
Just checked it out and everything LGTM!

**Review by tbushman — APPROVED** [review]

**Comment by raisedadead** [comment]
> Sorry oh git master. Please forgive me...

You just care about your commits don't you? 
FYI, I am the git ninja :godmode:. not `master`, that's probably a guy called Torvalds! 

Anyways, in seriousness, pulling this down. Can you guide me with what I am looking to break and test?

**Comment by tbushman** [comment]
@raisedadead I think this can be merged. I pulled the Bouncey:get/stash branch and am running it fine and we need to incorporate these changes.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
